name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'
      - 'packages/types/**'
      - 'packages/utils/**'
      - 'packages/ai-tools/**'
      - 'Dockerfile'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Cloud SDK
        uses: google-github/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - name: Authorize Docker push
        run: gcloud auth configure-docker
      
      - name: Build and push container
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/innerflame-api .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/innerflame-api
      
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy innerflame-api \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/innerflame-api \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars "NODE_ENV=production" \
            --set-env-vars "PORT=8080" \
            --set-env-vars "ALLOWED_ORIGINS=${{ secrets.FRONTEND_URL }}" \
            --set-env-vars "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" \
            --set-env-vars "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" \
            --set-env-vars "CLAUDE_API_KEY=${{ secrets.CLAUDE_API_KEY }}" \
            --set-env-vars "CLAUDE_MODEL=${{ secrets.CLAUDE_MODEL }}" \
            --set-env-vars "CLAUDE_MAX_TOKENS=${{ secrets.CLAUDE_MAX_TOKENS }}"
      
      - name: Update deployment status
        run: |
          echo "Deployed innerflame-api to Cloud Run"
          echo "Service URL: $(gcloud run services describe innerflame-api --platform managed --region us-central1 --format 'value(status.url)')" 